sudo: required
language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm prune
  - npm install codecov
script:
 - npm run build:lib
 - npm run test
 - npm run e2e -- --code-coverage
 - codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
