sudo: required
language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - node_modules
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm prune
script:
 - npm run test
 - npm run e2e
 - npm run packagr
after_success:
  - sudo find -maxdepth 1 ! -name dist ! -name . -exec rm -rv -f {} \;
  - mv dist/* .
  - rmdir dist
  - npm pack
  - semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
